apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-0038
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rs-demos-wmyl-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-0038@sha256:7a856964ce83970a8870edfebe4737def89a8de40f3cb9a3d4f23457a61c6522
        name: main
        resources: {}
status: {}
